$ANSIBLE_VAULT;1.2;AES256;main
34393363343865393635353734623933383630343438343761343066336561633132613934323932
3365313961643839333637636637623237653432343633320a653561376465363238366263316337
38356561363837623433663233343735393333306536353232383363326335396333316333326462
6266313839636464380a623865646136613634643166303633383165663734313361643635366632
33616337626465346563623866366366333834303232666163323630333430316136646131613764
39646431333238316131613866666439326362643730633734333364646237643534343631613036
63366463366231383835373937316638333235646161316465373732326465643132383662386432
31303965303032346336323533376466633531366261636538383531656637393866653136363731
61356136376266336138623138636163313537623465663164613137623334333963376335383930
39613864353861393665303731633164663065613136313135343439646334396335616231656431
62646465343066376338613536623439343364306630303466373334613939346338356166336363
33303636306463666431643231646563396465323930666663303334356461373830373533633936
34643433383465623961323337383266306666383130396664623661326434653838366135373763
64326663373232626130616564306365303634303863613061343430643262636530326335383231
65626561343461326165626638343539333765393332666630303866333230303932363133393234
32396163656262613835333037623330343839666162376237323134613138643630663130646136
33393064643030363261653133313632653237303930653236336635366638303338313237366532
30343264643639643061336661383231306337333463353531366337393162333530373630393931
36626637636533663230363237643932626164656437373966393761663831353365343532616133
62396337363932303332376265343730666263316466613034303739373937613233363834643233
66303333626361653262393038356561616666373461313862336163346465303838313032366130
61343130316336636332623539336464616337376261303465636135323536346662336363613261
39313461383138633531383963613431666236313236623963616430646634666466336438396532
34646232323835333865323835666536623530646430323833646163343462613163666137373362
61653330613834326362353266356439343163663832373037396662616234366562323161373038
37353861396161393064656433646631333262363664663163333538313337616235383638393837
646663383230643035656134303530636139
