---
- name: Ensure Frigate directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /etc/frigate
    - /media/frigate

- name: Template Frigate config
  ansible.builtin.template:
    src: config.yml.j2
    dest: /etc/frigate/config.yml
    owner: root
    group: root
    mode: '0644'
